name = "MedKorrekt"
license = "MIT"
licenselink = ""
description = "A clean, professional theme for medical editing services"
homepage = "https://medkorrekt.de"
tags = ["medical", "professional", "minimal", "german"]
features = ["responsive", "accessible"]
min_version = "0.115.0"

[author]
  name = "Nicolas Matentzoglu"
